//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carppi_ProductosPorRestaurantes
    {
        public long ID { get; set; }
        public string IDdRestaurante { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<long> Categoria { get; set; }
        public bool Disponibilidad { get; set; }
        public long ComprasDelProducto { get; set; }
        public bool HasOptionsToSelect { get; set; }
    }
}
