//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarppiGrocery_Repartidores
    {
        public long ID { get; set; }
        public string FaceID_Repartidor { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<long> BuyOrderID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string FirebaseID { get; set; }
        public string StripeDeliverID { get; set; }
        public byte[] Foto_repartidor { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public bool IsAvailableForDeliver { get; set; }
        public Nullable<long> Region { get; set; }
        public Nullable<double> Rating_double { get; set; }
        public string Marca_Vehiculo { get; set; }
        public string Modelo_Vehiculo { get; set; }
        public string Placa { get; set; }
        public byte[] FotoDelVehiculo_ByteArray { get; set; }
        public string UltimoComentario { get; set; }
        public long DebtToDeliverMan { get; set; }
        public long LastTimeOfLogin { get; set; }
        public double MonetMadeByDeliverMan { get; set; }
        public string StripeHash { get; set; }
        public string FleetManagerHash { get; set; }
        public string ValidationCode { get; set; }
        public string Email { get; set; }
    }
}
