//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarppiRequestForDrive
    {
        public int ID { get; set; }
        public string FaceIDDriver { get; set; }
        public string FaceIDPassenger { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Stat { get; set; }
        public Nullable<double> LatitudViajePendiente { get; set; }
        public Nullable<double> LongitudViajePendiente { get; set; }
        public string Distance { get; set; }
        public string NameOfRequester { get; set; }
        public string NameOfPlace { get; set; }
        public string PaymentIntentID { get; set; }
        public Nullable<bool> IsRequestNotTimedOut { get; set; }
        public bool Accepted { get; set; }
        public Nullable<long> CreationTime { get; set; }
        public Nullable<double> OriginOfRequest_Latitude { get; set; }
        public Nullable<double> OriginOfRequest_Longitude { get; set; }
        public int GenderSearch { get; set; }
    }
}
