//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarppiREstaurant_MensajesClienteRestaurante
    {
        public long ID { get; set; }
        public string Mensaje { get; set; }
        public string FaceID_Sender { get; set; }
        public Nullable<long> BuyOrderID { get; set; }
        public Nullable<long> DateInSeconds { get; set; }
        public bool Entregado { get; set; }
        public bool Leido { get; set; }
    }
}
