//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carppi_ComentariosHaciaElPerfil
    {
        public long ID { get; set; }
        public string Comentario { get; set; }
        public string FaceID_OfComentedFolk { get; set; }
        public string FaceID_OfRater { get; set; }
        public Nullable<double> Rate { get; set; }
    }
}
