//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carppi_IndicesdeRestaurantes
    {
        public long ID { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> Region { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public byte[] Foto { get; set; }
        public string FacebookId { get; set; }
        public string FirebaseID { get; set; }
        public Nullable<int> contextualVailidationNumber { get; set; }
        public Nullable<int> TypeOfStore { get; set; }
        public string CarppiHash { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public Nullable<bool> VerificacionDecuenta { get; set; }
        public Nullable<bool> RegistroValidado { get; set; }
        public Nullable<bool> EstaAbierto { get; set; }
        public string Categorias { get; set; }
        public Nullable<long> Categoriasbitfield { get; set; }
        public bool IsATestRestaurant { get; set; }
        public string TimeZoneID { get; set; }
        public string SaturdayOpenningSchedule { get; set; }
        public string MondayOpenningSchedule { get; set; }
        public string TuesdayOpenningSchedule { get; set; }
        public string WednesdayOpenningSchedule { get; set; }
        public string ThursDayOpenningSchedule { get; set; }
        public string FridayOpenningSchedule { get; set; }
        public string SunDayOpenningSchedule { get; set; }
        public string StripeAccount { get; set; }
        public string StripeHash { get; set; }
        public long DebtToRestaurant { get; set; }
        public string WebsitePasword { get; set; }
        public string WebsiteFirebaseHash { get; set; }
    }
}
