//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fotos_de_coches
    {
        public int ID { get; set; }
        public string Id_de_publicacion { get; set; }
        public string Foto { get; set; }
        public Nullable<int> Indicie_de_foto { get; set; }
        public Nullable<int> indice_de_foto_temporal { get; set; }
        public Nullable<int> cadena_de_foto_temporal { get; set; }
    }
}
