//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lease_Interrutores
    {
        public int ID { get; set; }
        public string Casa { get; set; }
        public string Habitacion { get; set; }
        public string Indice { get; set; }
        public string Alias { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Instruccion { get; set; }
        public Nullable<bool> Es_Dimmer { get; set; }
        public Nullable<int> Porcentaje_dimming { get; set; }
    }
}
