//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travelers_Mensajes_Grupos_de_Conversacion
    {
        public int ID { get; set; }
        public string Id_de_conversacion { get; set; }
        public string FaceIdDeConductor { get; set; }
        public string FaceIdDePasajero { get; set; }
        public string Mensaje { get; set; }
        public Nullable<bool> MensajeGrupal { get; set; }
        public Nullable<bool> Entregado { get; set; }
        public Nullable<bool> Leido { get; set; }
        public string NameOfSender { get; set; }
    }
}
