//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traveler_SolicitudDeViajeTemporal
    {
        public int ID { get; set; }
        public string Face_id_solicitante { get; set; }
        public Nullable<int> Estado_De_solicitud { get; set; }
        public Nullable<int> Id_del_viaje { get; set; }
        public Nullable<int> TipoDePago { get; set; }
        public string MoneyOwnedToDriver { get; set; }
        public string PaymentIntentID { get; set; }
        public string StripeCharge { get; set; }
    }
}
