//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traveler_Perfil
    {
        public int ID { get; set; }
        public string Nombre_usuario { get; set; }
        public string Numero_de_telefono { get; set; }
        public string Correo { get; set; }
        public string Resenas { get; set; }
        public string Edad { get; set; }
        public Nullable<bool> Telefono_verificado { get; set; }
        public string Stripe_id { get; set; }
        public string Facebook_profile_id { get; set; }
        public Nullable<int> Rol { get; set; }
        public string Viaje_asociado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<int> pidiendo_viaje { get; set; }
        public string Latitud_un_decimal { get; set; }
        public string Longitud_un_decimal { get; set; }
        public Nullable<bool> TarjetaValidada { get; set; }
        public Nullable<bool> IdentidadComprobada { get; set; }
        public string Telefono { get; set; }
        public string Foto { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FirebaseID { get; set; }
        public string StripeClientID { get; set; }
        public string StripeDriverID { get; set; }
        public string BusquedaGuardada_Latitud_salida { get; set; }
        public string BusquedaGuardada_Longitud_salida { get; set; }
        public string BusquedaGuardada_Latitud_Llegada { get; set; }
        public string BusquedaGuardada_Longitud_Llegada { get; set; }
        public int Rating { get; set; }
        public double Rating_double { get; set; }
        public Nullable<long> Region { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<double> LatitudObjetivoRideSharer { get; set; }
        public Nullable<double> LongitudObjetivoRideSharer { get; set; }
        public Nullable<double> StripeLastPaymentIntent { get; set; }
        public string StripeLastPaymentIntent_ID { get; set; }
        public byte[] Foto_ByteArray { get; set; }
        public byte[] FotoDelVehiculo_ByteArray { get; set; }
        public string Placa { get; set; }
        public string Modelo_Vehiculo { get; set; }
        public string Marca_Vehiculo { get; set; }
        public string Color_Vehiculo { get; set; }
        public bool hasConfirmedGender { get; set; }
        public string PaymentMethod { get; set; }
        public bool IsUserADriver { get; set; }
        public Nullable<long> Region_ReparticionDeAlimentos { get; set; }
        public bool IsFirstOrder { get; set; }
        public bool IsUserAJoker { get; set; }
        public Nullable<long> AmountOfJoke { get; set; }
    }
}
