//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traveler_Viajes_historial
    {
        public int ID { get; set; }
        public string Inicio { get; set; }
        public string Destino { get; set; }
        public string Kilometros { get; set; }
        public string Tiempo_estimado { get; set; }
        public Nullable<System.DateTime> Fecha_y_hora { get; set; }
        public string Pasajeros_numero { get; set; }
        public string Pasajeros_IDS { get; set; }
        public string FaceIdDelConductor { get; set; }
        public string TimeData { get; set; }
        public string Costo_por_Usuario { get; set; }
        public string CobroPorPasajero { get; set; }
        public string GananciaConductor { get; set; }
        public string GananciaCarppi { get; set; }
        public string ComicionMotorPago { get; set; }
        public Nullable<int> PasajerosQuePagaronConTarjeta { get; set; }
    }
}
