//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trayectorias_geoloc
    {
        public int ID { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Dispositivo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
