//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrbanCabTripRequest
    {
        public int TripRequestNumberID { get; set; }
        public string DriverID { get; set; }
        public string ClientID { get; set; }
        public string Latitud_Origen { get; set; }
        public string Longitud_Origen { get; set; }
        public string Latitud_Destino { get; set; }
        public string Longitud_Destino { get; set; }
        public string PrecioSugerido { get; set; }
        public string Precio { get; set; }
        public bool Aceptado { get; set; }
    }
}
