//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas_lista
    {
        public int ID { get; set; }
        public Nullable<int> Indicie_recibo { get; set; }
        public string Tienda { get; set; }
        public string articulo { get; set; }
    }
}
