//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarppiGrocery_BuyOrders
    {
        public long ID { get; set; }
        public Nullable<long> RegionID { get; set; }
        public string UserID { get; set; }
        public string paymentIntent { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<int> Stat { get; set; }
        public string ListaDeProductos { get; set; }
        public Nullable<double> Latitud_Repartidor { get; set; }
        public Nullable<double> Longitud_Repartidor { get; set; }
        public Nullable<double> FaceIDRepartidor_Repartidor { get; set; }
        public string FaceIDRepartidor_RepartidorCadena { get; set; }
        public string NombreDelUsuario { get; set; }
        public Nullable<int> TipoDePago { get; set; }
    }
}
