//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarppiConductoresRideShare
    {
        public int ID { get; set; }
        public string NombreUsuario { get; set; }
        public string ApellidoUsuario { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string FirebaseID { get; set; }
        public string StripeDriverID { get; set; }
        public string FaceBookProfileId { get; set; }
        public Nullable<long> Region { get; set; }
        public Nullable<long> Viajes { get; set; }
        public Nullable<long> TripID { get; set; }
        public Nullable<bool> Disponible { get; set; }
        public Nullable<double> Reseñas { get; set; }
        public Nullable<double> LatitudActual { get; set; }
        public Nullable<double> LongitudActual { get; set; }
        public Nullable<double> LatitudObjetivo { get; set; }
        public Nullable<double> LongitudObjetivo { get; set; }
    }
}
