//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PidgeonEntities : DbContext
    {
        public PidgeonEntities()
            : base("name=PidgeonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carppi_ComentariosHaciaElPerfil> Carppi_ComentariosHaciaElPerfil { get; set; }
        public virtual DbSet<Carppi_IndicesdeRestaurantes> Carppi_IndicesdeRestaurantes { get; set; }
        public virtual DbSet<Carppi_MensajesRideshare> Carppi_MensajesRideshare { get; set; }
        public virtual DbSet<Carppi_ProductosPorRestaurantes> Carppi_ProductosPorRestaurantes { get; set; }
        public virtual DbSet<CarppiConductoresRideShare> CarppiConductoresRideShare { get; set; }
        public virtual DbSet<CarppiGrocery_BuyOrders> CarppiGrocery_BuyOrders { get; set; }
        public virtual DbSet<CarppiGrocery_Mensajes> CarppiGrocery_Mensajes { get; set; }
        public virtual DbSet<CarppiGrocery_Productos> CarppiGrocery_Productos { get; set; }
        public virtual DbSet<CarppiGrocery_Regiones> CarppiGrocery_Regiones { get; set; }
        public virtual DbSet<CarppiGrocery_Repartidores> CarppiGrocery_Repartidores { get; set; }
        public virtual DbSet<CarppiRegiones> CarppiRegiones { get; set; }
        public virtual DbSet<CarppiRequestForDrive> CarppiRequestForDrive { get; set; }
        public virtual DbSet<Coches_en_renta> Coches_en_renta { get; set; }
        public virtual DbSet<Dispositivos> Dispositivos { get; set; }
        public virtual DbSet<Fotos_de_coches> Fotos_de_coches { get; set; }
        public virtual DbSet<GenInstruccionesAccesos> GenInstruccionesAccesos { get; set; }
        public virtual DbSet<Lease_FotosPublicacion> Lease_FotosPublicacion { get; set; }
        public virtual DbSet<Lease_Interrutores> Lease_Interrutores { get; set; }
        public virtual DbSet<Lease_Publicaciones> Lease_Publicaciones { get; set; }
        public virtual DbSet<Local_> Local_ { get; set; }
        public virtual DbSet<Pos_Fotos_productos> Pos_Fotos_productos { get; set; }
        public virtual DbSet<PosUsers> PosUsers { get; set; }
        public virtual DbSet<Prestamos_Monedas> Prestamos_Monedas { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Traveler_Perfil> Traveler_Perfil { get; set; }
        public virtual DbSet<Traveler_SolicitudDeViajeTemporal> Traveler_SolicitudDeViajeTemporal { get; set; }
        public virtual DbSet<Traveler_Viajes> Traveler_Viajes { get; set; }
        public virtual DbSet<Traveler_Viajes_historial> Traveler_Viajes_historial { get; set; }
        public virtual DbSet<Travelers_Grupos_de_Conversacion> Travelers_Grupos_de_Conversacion { get; set; }
        public virtual DbSet<Travelers_Integrantes_Grupos_de_Conversacion> Travelers_Integrantes_Grupos_de_Conversacion { get; set; }
        public virtual DbSet<Travelers_Mensajes_Grupos_de_Conversacion> Travelers_Mensajes_Grupos_de_Conversacion { get; set; }
        public virtual DbSet<Trayectorias_geoloc> Trayectorias_geoloc { get; set; }
        public virtual DbSet<UrbanCabDrivers> UrbanCabDrivers { get; set; }
        public virtual DbSet<UrbanCabNewTrip> UrbanCabNewTrip { get; set; }
        public virtual DbSet<UrbanCabPassengers> UrbanCabPassengers { get; set; }
        public virtual DbSet<UrbanCabTripRequest> UrbanCabTripRequest { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<Ventas_lista> Ventas_lista { get; set; }
        public virtual DbSet<CarppiRestaurant_BuyOrders> CarppiRestaurant_BuyOrders { get; set; }
        public virtual DbSet<CarppiREstaurant_MensajesClienteRestaurante> CarppiREstaurant_MensajesClienteRestaurante { get; set; }
        public virtual DbSet<CarppiRestaurant_MensajesRepartidorCliente> CarppiRestaurant_MensajesRepartidorCliente { get; set; }
        public virtual DbSet<CarppiRestaurant_MensajesRepartidorRestaurante> CarppiRestaurant_MensajesRepartidorRestaurante { get; set; }
        public virtual DbSet<ObligatoriOptionsList> ObligatoriOptionsList { get; set; }
        public virtual DbSet<OpcionalOptionsList> OpcionalOptionsList { get; set; }
        public virtual DbSet<OptionalChoice> OptionalChoice { get; set; }
    }
}
