//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int ID { get; set; }
        public string Nombre_de_producto { get; set; }
        public Nullable<int> Existencias { get; set; }
        public byte[] Foto { get; set; }
        public string Tienda { get; set; }
        public string Descripcion { get; set; }
        public string Id_de_la_tienda { get; set; }
        public Nullable<double> Costo { get; set; }
    }
}
