//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travelers_Grupos_de_Conversacion
    {
        public int ID { get; set; }
        public string AliasConversacion { get; set; }
        public string FaceIdDeConductor { get; set; }
        public string FaceIdDePasajero { get; set; }
        public Nullable<bool> IsGroupConversation { get; set; }
        public Nullable<bool> HasDriverSeenIt { get; set; }
        public Nullable<bool> HaspassengerSeenIt { get; set; }
    }
}
