//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrbanCabDrivers
    {
        public int DriverID { get; set; }
        public string Nombre { get; set; }
        public string StripeID { get; set; }
        public string OpenPayID { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Calificacion { get; set; }
        public string clabe { get; set; }
        public string ClienteID { get; set; }
        public bool Identidad_validada { get; set; }
        public bool Numero_validado { get; set; }
        public bool Correo_validado { get; set; }
        public byte[] Foto { get; set; }
        public string Matricula { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string FaceID { get; set; }
        public Nullable<bool> AvailableToDrive { get; set; }
    }
}
