//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoLoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarppiRegione
    {
        public int ID { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public Nullable<double> LatitudCentroide { get; set; }
        public Nullable<double> LongitudCentroide { get; set; }
        public Nullable<long> ServicioRegional { get; set; }
        public Nullable<double> Radio { get; set; }
        public string Pais { get; set; }
        public string CountryCoin { get; set; }
    }
}
