//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarppiRestaurant_BuyOrders
    {
        public long ID { get; set; }
        public Nullable<long> RegionID { get; set; }
        public string UserID { get; set; }
        public string paymentIntent { get; set; }
        public Nullable<double> LatitudPeticion { get; set; }
        public Nullable<double> LongitudPeticion { get; set; }
        public Nullable<double> LatitudRestaurante { get; set; }
        public Nullable<double> LongitudRestaurante { get; set; }
        public Nullable<double> LatitudRepartidor { get; set; }
        public Nullable<double> LongitudRepartidor { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> Stat { get; set; }
        public string RestaurantHash { get; set; }
        public string NombreDelRestaurante { get; set; }
        public string NombreDelUsuario { get; set; }
        public string ListaDeProductos { get; set; }
        public string FaceIDRepartidor_RepartidorCadena { get; set; }
        public Nullable<int> TipoDePago { get; set; }
        public bool RestaurantToDisplayOrders { get; set; }
        public bool ReparidorEnElAreaDelRestaurante { get; set; }
        public bool ReparidorEnElAreaDelCliente { get; set; }
        public double CostoDeTransporte { get; set; }
        public double TarifaDelServicio { get; set; }
        public string Comentario { get; set; }
        public long TimeOfCreation { get; set; }
        public string StripeChargeID { get; set; }
    }
}
