//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coches_en_renta
    {
        public int ID { get; set; }
        public string Modelo { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public string Arrendatario { get; set; }
        public string Costo { get; set; }
        public Nullable<int> Disponibilidad { get; set; }
        public string Relacion_base_fotografias { get; set; }
    }
}
