//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivos
    {
        public int ID { get; set; }
        public string Dispositivo { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Hora { get; set; }
        public Nullable<System.DateTime> Fecha_Activacion { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Contrato { get; set; }
        public string Saldo { get; set; }
        public Nullable<bool> Vigente { get; set; }
        public string Velocidad { get; set; }
    }
}
