//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenInstruccionesAccesos
    {
        public int ID { get; set; }
        public string Cuenta { get; set; }
        public string dispositivo { get; set; }
        public string instruccion { get; set; }
        public Nullable<bool> leido { get; set; }
    }
}
