//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalChoice
    {
        public long ID { get; set; }
        public long IDdelProducto { get; set; }
        public long IDdelConjunto { get; set; }
        public int EsPersonal { get; set; }
        public string OptionHash { get; set; }
        public Nullable<double> CostoExtra { get; set; }
        public bool Disponible { get; set; }
    }
}
