//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pos_Fotos_productos
    {
        public int ID { get; set; }
        public Nullable<int> ID_de_producto { get; set; }
        public byte[] Foto_de_Producto { get; set; }
    }
}
