//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traveler_Viajes
    {
        public int ID { get; set; }
        public string Inicio { get; set; }
        public string Destino { get; set; }
        public string Kilometros { get; set; }
        public string Tiempo_estimado { get; set; }
        public string Vehiculo { get; set; }
        public Nullable<System.DateTime> Fecha_y_hora { get; set; }
        public string asientos_disponibles { get; set; }
        public Nullable<bool> Disponible { get; set; }
        public Nullable<bool> En_curso { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<int> Estado_del_viaje { get; set; }
        public string FaceIdDelConductor { get; set; }
        public string Latitud_destino { get; set; }
        public string Longitud_destino { get; set; }
        public string TimeData { get; set; }
        public string Costo_po_Usuario { get; set; }
        public string Viaje_Periodico { get; set; }
        public string Asientos_Totales { get; set; }
        public Nullable<bool> Conductor_a_asociado_su_tarjeta { get; set; }
        public string PaisOrigen { get; set; }
        public string PaisDestino { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> Privado { get; set; }
        public Nullable<int> TipoDePago { get; set; }
        public Nullable<int> DiaDeViaje { get; set; }
        public Nullable<int> MesDeViaje { get; set; }
        public Nullable<int> AnoDeViaje { get; set; }
    }
}
