//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travelers_Integrantes_Grupos_de_Conversacion
    {
        public int ID { get; set; }
        public string Id_de_conversacion { get; set; }
        public string FaceIdDeIntegrante { get; set; }
        public Nullable<bool> IsGroupAdministrator { get; set; }
        public bool HasSeenMesageInGroup { get; set; }
    }
}
