//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarppiWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int ID { get; set; }
        public string Tendero { get; set; }
        public string Tienda { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
